import React from 'react';
import { Container } from 'react-bootstrap';
import { Link } from 'react-router-dom';

const Terms = () => {
    return (
        <Container>
            <h2>Our Terms & Conditions</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis ipsum obcaecati cupiditate nisi consequuntur. Vero pariatur quidem, reiciendis nemo mollitia ducimus eius neque? Nisi aperiam rerum harum accusantium aspernatur qui itaque et temporibus. Ducimus exercitationem expedita consequuntur, maiores numquam illo cumque quae corrupti sit neque sapiente eligendi quasi odio dignissimos nobis, placeat, minus in voluptatem. Fuga ad consectetur earum fugiat cum tempore voluptate nihil perferendis, quae sit pariatur ab. Ex illum rem nesciunt quae laborum! Nesciunt atque totam consequuntur natus dignissimos soluta eius quasi eum. Itaque dolore at error modi incidunt, delectus doloribus, expedita repudiandae exercitationem, iste blanditiis dolor ipsum est! Debitis, consectetur facilis. Temporibus necessitatibus corrupti voluptatibus omnis odio cum placeat consectetur molestias voluptates libero in quod fugit nulla eaque eveniet, sint odit itaque rerum, autem perferendis. Temporibus animi ea molestiae. Voluptates facere voluptatem molestiae laborum quae possimus deserunt officia maiores molestias eveniet quidem unde dolorum, porro numquam laboriosam perferendis. Nam, harum doloremque quam, modi aspernatur atque corrupti fugit, cum ea tempora assumenda asperiores eaque dignissimos odit voluptas beatae. Praesentium perspiciatis saepe vel eum modi nobis soluta eaque laboriosam quam a! Necessitatibus accusamus iure quasi, totam quam laborum natus at sint vel nesciunt maxime. Nemo id libero provident laboriosam! Ea, itaque pariatur velit sed repudiandae saepe dolore asperiores explicabo recusandae libero, unde est numquam eaque commodi atque ducimus accusantium enim officiis iste. Accusamus expedita ut quidem error et pariatur tenetur iste nostrum animi at fugiat illo iusto veniam aliquam perspiciatis laudantium doloribus, veritatis sapiente ipsam culpa adipisci amet. Delectus, illum reiciendis nostrum id eos eius. Delectus obcaecati accusantium iure rem. Debitis distinctio voluptate tempora aliquam nemo ut atque incidunt nam sint iste quibusdam, rem accusamus illo? Eius quam soluta ad reprehenderit dolorem temporibus ea id itaque neque ex tenetur consectetur esse ab, iste aspernatur explicabo blanditiis minus quis? Sunt!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis maiores magni tenetur, vel cupiditate voluptatem obcaecati nam, ullam temporibus officia neque. Illum sunt amet quod dolorem molestias ea ad doloremque laborum itaque deleniti officiis vel quasi repudiandae voluptatum natus velit obcaecati, dolore magni inventore dicta similique nam, iure atque veniam. Magnam, perspiciatis deleniti odit voluptates quia libero excepturi repellat eos corporis incidunt? Sed inventore ex voluptas ratione, quasi repellat temporibus vero dignissimos magni reprehenderit iusto voluptates libero repudiandae possimus, quae porro officia hic minus ut expedita ab. Officiis laudantium voluptas aliquid sit sequi consectetur facere! Esse distinctio veritatis cumque aliquid.</p>
            <Link to="/register">Back to register</Link>
        </Container>
    );
};

export default Terms;